from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/update/', views.update_cart, name='update_cart'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('addresses/', views.address_list_view, name='address_list'),
    path('add-address/', views.save_address, name='save_address'),
    path('address/<int:address_id>/', views.address_detail, name='address_detail'),
    path('update-cart/', views.update_cart_ajax, name='update_cart_ajax'),
    path('place-order/', views.place_order_from_cart, name='place_order'),
    path('buy-now/<int:product_id>/', views.buy_now, name='buy_now'),
    path('verify-payment/', views.verify_payment, name='verify_payment'),
    path('set-selected-address/', views.set_selected_address, name='set_selected_address'),
    path('order-summary/', views.order_summary, name='order_summary'),
    path('submit-review/', views.submit_review, name='submit_review'),
    path('edit-address/', views.edit_address, name='edit_address'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('about-us/', views.about_us, name='about_us'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms-conditions/', views.terms_conditions, name='terms_conditions'),
    path('return-policy/', views.return_policy, name='return_policy'),
    path('profile/', views.user_profile, name='user_profile'),
    path('edit-address/<int:address_id>/', views.edit_address_for_user_profile, name='edit_address_for_user_profile'),
    path('delete-cart-item/', views.delete_cart_item, name='delete_cart_item'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('order/cancel/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('phone_login/', views.phone_login_view, name='phone_login'),
    path('firebase-login-callback/', views.firebase_login_callback, name='firebase_login_callback'),

]
